use-nnet2: True
decoder:
    # All the properties nested here correspond to the kaldinnet2onlinedecoder GStreamer plugin properties.
    # Use gst-inspect-1.0 ./libgstkaldionline2.so kaldinnet2onlinedecoder to discover the available properties
    nnet-mode: 3
    use-threaded-decoder: true
    model : /opt/models/tdnn_7b_chain_online/final.mdl
    word-syms : /opt/models/tdnn_7b_chain_online/graph_pp/words.txt
    phone-syms: /opt/models/tdnn_7b_chain_online/graph_pp/phones.txt
    word-boundary-file: /opt/models/tdnn_7b_chain_online/graph_pp/phones/word_boundary.int
    do-phone-alignment: true
    fst : /opt/models/tdnn_7b_chain_online/graph_pp/HCLG.fst
    mfcc-config : /opt/models/tdnn_7b_chain_online/conf/mfcc.conf
    ivector-extraction-config : /opt/models/tdnn_7b_chain_online/conf/ivector_extractor.conf
    max-active: 20000
    beam: 15.0
    lattice-beam: 6.0
    acoustic-scale: 1.0
    do-endpointing : true
    endpoint-silence-phones : "1:2:3:4:5:6:7:8:9:10:11:12:13:14:15:16:17:18:19:20"
    traceback-period-in-secs: 0.25
    chunk-length-in-secs: 0.25
    num-nbest: 10
    frame-subsampling-factor: 3
    #Additional functionality that you can play with:
    #lm-fst:  test/models/english/tedlium_nnet_ms_sp_online/G.fst
    #big-lm-const-arpa: test/models/english/tedlium_nnet_ms_sp_online/G.carpa
out-dir: /tmp

use-vad: False
silence-timeout: 10

# Just a sample post-processor that appends "." to the hypothesis
#post-processor: perl -npe 'BEGIN {use IO::Handle; STDOUT->autoflush(1);} s/(.*)/\1./;'

# A sample full post processor that add a confidence score to 1-best hyp and deletes other n-best hyps
#full-post-processor: ./sample_full_post_processor.py

logging:
    version : 1
    disable_existing_loggers: False
    formatters:
        simpleFormater:
            format: '%(asctime)s - %(levelname)7s: %(name)10s: %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simpleFormater
            level: DEBUG
    root:
        level: DEBUG
        handlers: [console]
